#!/bin/sh

TOP_LEVEL=$(git rev-parse --show-toplevel)

if command -v swiftformat >/dev/null 2>&1
then
    echo "Checking formatting..."
    DIFF_BEFORE=$(git diff)
    (cd "$TOP_LEVEL" && swiftformat .)
    DIFF_AFTER=$(git diff)
    
    # check if swiftformat changed any files
    if [ "$DIFF_BEFORE" != "$DIFF_AFTER" ]
    then
        echo "Error: Files were modified by the formatter."
        echo "stage the changes and try again."
        exit 1
    fi
else
    echo "Warning: swiftformat not found."
    exit 1
fi

if command -v swiftlint >/dev/null 2>&1
then
    echo "Running SwiftLint..."
		(cd "$TOP_LEVEL/ios" && swiftlint --strict --config .swiftlint.yml)
    # the script will exit here if swiftlint fails
else
    echo "Warning: swiftlint not found."
    exit 1
fi
