#!/bin/sh

TOP_LEVEL=$(git rev-parse --show-toplevel)

if command -v swiftformat >/dev/null 2>&1
then
    echo "Checking formatting..."
    (cd "$TOP_LEVEL" && swiftformat .)
    
    # check if swiftformat changed any files
    if ! git diff --exit-code >/dev/null 2>&1
    then
        echo "Error: Files were modified by the formatter."
        echo "stage the changes and try again."
        exit 1
    fi
else
    echo "Warning: swiftformat not found."
    exit 1
fi

if command -v swiftlint >/dev/null 2>&1
then
    echo "Running SwiftLint..."
    (cd "$TOP_LEVEL" && swiftlint)
    # the script will exit here if swiftlint fails
else
    echo "Warning: swiftlint not found."
    exit 1
fi
