#!/bin/sh
#
# Place appropriately named executable hook scripts into this directory
# to intercept various actions that git takes.  See `git help hooks` for
# more information.
if command -v swiftformat >/dev/null 2>&1
then
    echo "Running SwiftFormat"
    (cd "$(git rev-parse --show-toplevel)/ios" && swiftformat .)
else
    echo "Warning: `swiftformat` command not found - run the command: brew install swiftformat"
fi

if command -v swiftlint >/dev/null 2>&1
then
    echo "Running SwiftLint"
    (cd "$(git rev-parse --show-toplevel)/ios" && swiftlint --force-exclude)
else
    echo "Warning: `swiftlint` command not found - run the command: brew install swiftlint"
fi
