name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: swift:6.1
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test --skip-build
