name: Freerooms CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer

jobs:
  lint:
    name: Run lint
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
      working-directory: ios
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
  tests:
    name: Run tests
    runs-on: macos-15
    defaults:
      run:
        working-directory: ios
    steps:
    - uses: actions/checkout@v4
    - name: Run Networking tests
      run: xcodebuild test -scheme Networking
    - name: Run Location tests
      run: xcodebuild test -scheme Location
    - name: Run Buildings tests
      run: xcodebuild test -scheme Buildings
  build:
    name: Run build
    runs-on: macos-15
    defaults:
      run:
        working-directory: ios
    steps:
    - uses: actions/checkout@v4
    - name: build swift project
      run: xcodebuild
