name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cd ios && xcodebuild test -scheme Networkingachmen
