name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: macos-15
    steps:
      - uses: swift-actions/setup-swift@v2

      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v4

      - name: Test
        run: cd ios && xcodebuild test -scheme Networkingachmen
